<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'content',
        'meta_description',
        'meta_keywords',
        'published_at'
    ];

    protected $casts = [
        'published_at' => 'datetime'
    ];

    /**
     * Get the author of this blog.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $separator = '-';

            $slug = str_replace(
                ' ',
                $separator,
                substr(strtolower(htmlentities($model->title)), 0, 255));

            $i = 0;

            while (static::where('slug', $slug)->exists() || $slug === '') {
                $slug = $slug.$separator.$i++;
            }

            $model->slug = $slug;

            if (! app()->runningInConsole()) {
                // Assigning a user id
                $model->user_id = request()->user()->id;
            }
        });
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}
